package:
  name: intake-parquet
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake>=0.2
    - python
    - pandas
    - dask
    - fastparquet

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_parquet tests

about:
  home: https://github.com/ContinuumIO/intake-parquet
  license: BSD
  license_file: LICENSE
  summary: Intake parquet plugin
